import { apiRequest } from './client'
export interface ReviewTask { id: string; project_id?: string; root_id: string; raw_fact_id: string | null; batch_id: string | null; subject: string; property: string; value: string; reviewer_id: string | null; lease_expires_at: string | null; lease_version: number; status: string; created_at: string }
export interface ReviewBatchSummary { batch_id: string; created_at: string; preset: string; total: number; pending: number; claimed: number; completed: number }
export interface FactVersion { id?: string; root_id?: string; raw_fact_id?: string | null; version_number: number; action?: string; row_json: Record<string, string>; editable_values?: Record<string, string>; created_at?: string }
export const listReviewBatches = (projectId: string, signal?: AbortSignal) => apiRequest<{ items: ReviewBatchSummary[]; total: number }>(`/api/projects/${projectId}/review-batches`, { signal })
export const listReviewTasks = (projectId: string, options: { status?: string; reviewerId?: string; batchId?: string; offset?: number; limit?: number; signal?: AbortSignal } = {}) => { const query = new URLSearchParams({ limit: String(options.limit ?? 25), offset: String(options.offset ?? 0) }); if (options.status) query.set('status', options.status); if (options.reviewerId) query.set('reviewer_id', options.reviewerId); if (options.batchId) query.set('batch_id', options.batchId); return apiRequest<{ items: ReviewTask[]; total: number; offset: number; limit: number }>(`/api/projects/${projectId}/review-tasks?${query}`, { signal: options.signal }) }
export const claimReviewTask = (projectId: string, taskId: string) => apiRequest<ReviewTask>(`/api/projects/${projectId}/review-tasks/${taskId}/claim`, { method: 'POST' })
export const claimReviewTaskBatch = (projectId: string, taskIds: string[]) => apiRequest<{ items: ReviewTask[]; skipped_task_ids: string[] }>(`/api/projects/${projectId}/review-tasks/claim-batch`, { method: 'POST', body: JSON.stringify({ task_ids: taskIds }) })
export const renewReviewTask = (projectId: string, task: ReviewTask) => apiRequest<ReviewTask>(`/api/projects/${projectId}/review-tasks/${task.id}/renew`, { method: 'POST', body: JSON.stringify({ expected_version: task.lease_version }) })
export const releaseReviewTask = (projectId: string, task: ReviewTask) => apiRequest<ReviewTask>(`/api/projects/${projectId}/review-tasks/${task.id}/release`, { method: 'POST', body: JSON.stringify({ expected_version: task.lease_version }) })
export const getFactVersions = (projectId: string, factId: string) => apiRequest<{ items: FactVersion[] }>(`/api/projects/${projectId}/facts/${factId}/versions?limit=100`)
export const getRootVersions = (projectId: string, rootId: string) => apiRequest<{ items: FactVersion[] }>(`/api/projects/${projectId}/review-facts/${rootId}/versions?limit=100`)
export const listCurrentFacts = (projectId: string, signal?: AbortSignal) => apiRequest<{ items: FactVersion[]; total: number }>(`/api/projects/${projectId}/current-facts?limit=100`, { signal })
export const createReviewTask = (projectId: string, rootId: string) => apiRequest<ReviewTask>(`/api/projects/${projectId}/review-tasks`, { method: 'POST', body: JSON.stringify({ root_id: rootId }) })
export const createRawFactReviewTask = (projectId: string, factId: string) => apiRequest<ReviewTask>(`/api/projects/${projectId}/review-tasks`, { method: 'POST', body: JSON.stringify({ fact_id: factId }) })
export const submitReview = (projectId: string, task: ReviewTask, version: FactVersion, action: string, patch: Record<string, string>, idempotencyKey: string) => apiRequest<FactVersion>(`/api/projects/${projectId}/review-facts/${task.root_id}/reviews`, { method: 'POST', body: JSON.stringify({ action, patch, expected_version: version.version_number, review_task_id: task.id, expected_lease_version: task.lease_version, idempotency_key: idempotencyKey }) })
export const createManualFact = (projectId: string, fields: Record<string, string>) => apiRequest<FactVersion>(`/api/projects/${projectId}/manual-facts`, { method: 'POST', body: JSON.stringify({ fields, idempotency_key: crypto.randomUUID() }) })
