"""immutable collaborative review roots, versions and leases"""
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa

revision: str = "0009_reviews"
down_revision: str | None = "0008_model_usage"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _common(): return [sa.Column("id",sa.Uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False)]


def upgrade() -> None:
    op.create_table("review_fact_roots",*_common(),sa.Column("project_id",sa.Uuid(),nullable=False),sa.Column("raw_fact_id",sa.Uuid()),sa.Column("document_id",sa.Uuid()),sa.Column("document_version_id",sa.Uuid()),sa.Column("source",sa.String(16),nullable=False),sa.Column("created_by_id",sa.Uuid(),nullable=False),sa.CheckConstraint("source IN ('raw','manual')",name="ck_review_root_source"),sa.CheckConstraint("(source='raw' AND raw_fact_id IS NOT NULL) OR (source='manual' AND raw_fact_id IS NULL)",name="ck_review_root_source_link"),sa.ForeignKeyConstraint(["project_id"],["projects.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["raw_fact_id"],["raw_facts.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["document_id"],["documents.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["document_version_id"],["document_versions.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["created_by_id"],["users.id"],ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("raw_fact_id",name="uq_review_root_raw_fact"))
    op.create_index("ix_review_fact_roots_project_id","review_fact_roots",["project_id"]);op.create_index("ix_review_fact_roots_raw_fact_id","review_fact_roots",["raw_fact_id"])
    op.create_table("review_tasks",*_common(),sa.Column("project_id",sa.Uuid(),nullable=False),sa.Column("root_id",sa.Uuid(),nullable=False),sa.Column("reviewer_id",sa.Uuid()),sa.Column("lease_expires_at",sa.DateTime(timezone=True)),sa.Column("lease_version",sa.Integer(),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.CheckConstraint("status IN ('pending','claimed','completed')",name="ck_review_task_status"),sa.CheckConstraint("lease_version>=0",name="ck_review_task_lease_version"),sa.CheckConstraint("(status='pending' AND reviewer_id IS NULL AND lease_expires_at IS NULL) OR (status='claimed' AND reviewer_id IS NOT NULL AND lease_expires_at IS NOT NULL) OR (status='completed' AND reviewer_id IS NOT NULL AND lease_expires_at IS NULL)",name="ck_review_task_lease_state"),sa.ForeignKeyConstraint(["project_id"],["projects.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["root_id"],["review_fact_roots.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["reviewer_id"],["users.id"],ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id"))
    for c in ("project_id","root_id","reviewer_id","lease_expires_at","status"):op.create_index(f"ix_review_tasks_{c}","review_tasks",[c])
    op.create_index("uq_review_task_active_root","review_tasks",["root_id"],unique=True,sqlite_where=sa.text("status != 'completed'"),postgresql_where=sa.text("status != 'completed'"))
    op.create_table("fact_versions",*_common(),sa.Column("root_id",sa.Uuid(),nullable=False),sa.Column("project_id",sa.Uuid(),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("actor_id",sa.Uuid(),nullable=False),sa.Column("action",sa.String(32),nullable=False),sa.Column("row_json",sa.JSON(),nullable=False),sa.Column("patch_json",sa.JSON(),nullable=False),sa.Column("audit_json",sa.JSON(),nullable=False),sa.Column("is_tombstone",sa.Boolean(),nullable=False),sa.Column("is_published",sa.Boolean(),nullable=False),sa.Column("idempotency_key",sa.String(128),nullable=False),sa.Column("request_fingerprint",sa.String(64),nullable=False),sa.Column("review_task_id",sa.Uuid()),sa.Column("review_lease_version",sa.Integer()),sa.CheckConstraint("version_number>=1",name="ck_fact_version_number"),sa.CheckConstraint("action IN ('approve','modify_approve','reject','dispute','manual_create','delete','publish')",name="ck_fact_version_action"),sa.CheckConstraint("length(idempotency_key)>0 AND length(request_fingerprint)=64",name="ck_fact_version_request"),sa.CheckConstraint("(action='manual_create' AND review_task_id IS NULL AND review_lease_version IS NULL) OR (action!='manual_create' AND review_task_id IS NOT NULL AND review_lease_version IS NOT NULL)",name="ck_fact_version_review_task"),sa.ForeignKeyConstraint(["root_id"],["review_fact_roots.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["project_id"],["projects.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["actor_id"],["users.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["review_task_id"],["review_tasks.id"],ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("root_id","version_number",name="uq_fact_version_number"),sa.UniqueConstraint("root_id","idempotency_key",name="uq_fact_version_idempotency"),sa.UniqueConstraint("project_id","actor_id","idempotency_key",name="uq_fact_version_actor_request"))
    for c in ("root_id","project_id","actor_id","action","is_tombstone","is_published"):op.create_index(f"ix_fact_versions_{c}","fact_versions",[c])
    op.create_index("ix_fact_versions_review_task_id","fact_versions",["review_task_id"])
    dialect=op.get_bind().dialect.name
    if dialect=="sqlite":
        for table in ("review_fact_roots","fact_versions"):
            for action in ("UPDATE","DELETE"):op.execute(f"CREATE TRIGGER prevent_{table}_{action.lower()} BEFORE {action} ON {table} BEGIN SELECT RAISE(ABORT,'review history immutable'); END")
        op.execute("CREATE TRIGGER enforce_review_root_linkage BEFORE INSERT ON review_fact_roots WHEN (NEW.source='raw' AND NOT EXISTS(SELECT 1 FROM raw_facts f WHERE f.id=NEW.raw_fact_id AND f.project_id=NEW.project_id AND f.document_id=NEW.document_id AND f.document_version_id=NEW.document_version_id)) OR (NEW.document_version_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM document_versions v JOIN documents d ON d.id=v.document_id WHERE v.id=NEW.document_version_id AND d.id=NEW.document_id AND d.project_id=NEW.project_id)) OR (NEW.document_version_id IS NULL AND NEW.document_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM documents d WHERE d.id=NEW.document_id AND d.project_id=NEW.project_id)) BEGIN SELECT RAISE(ABORT,'review root linkage mismatch'); END")
        op.execute("CREATE TRIGGER enforce_fact_version_linkage BEFORE INSERT ON fact_versions WHEN NOT EXISTS(SELECT 1 FROM review_fact_roots r WHERE r.id=NEW.root_id AND r.project_id=NEW.project_id) OR NEW.version_number!=COALESCE((SELECT MAX(v.version_number) FROM fact_versions v WHERE v.root_id=NEW.root_id),0)+1 BEGIN SELECT RAISE(ABORT,'fact version linkage mismatch'); END")
        op.execute("CREATE TRIGGER enforce_fact_version_task BEFORE INSERT ON fact_versions WHEN (NEW.action!='manual_create' AND NOT EXISTS(SELECT 1 FROM review_tasks t WHERE t.id=NEW.review_task_id AND t.root_id=NEW.root_id AND t.project_id=NEW.project_id AND t.reviewer_id=NEW.actor_id AND t.status='claimed' AND t.lease_version=NEW.review_lease_version AND t.lease_expires_at>CURRENT_TIMESTAMP)) OR (NEW.action='manual_create' AND NOT EXISTS(SELECT 1 FROM review_fact_roots r WHERE r.id=NEW.root_id AND r.source='manual' AND r.created_by_id=NEW.actor_id AND NEW.version_number=1 AND NEW.review_task_id IS NULL AND NEW.review_lease_version IS NULL)) BEGIN SELECT RAISE(ABORT,'fact version task mismatch'); END")
        op.execute("CREATE TRIGGER enforce_review_task_linkage_insert BEFORE INSERT ON review_tasks WHEN NOT EXISTS(SELECT 1 FROM review_fact_roots r WHERE r.id=NEW.root_id AND r.project_id=NEW.project_id) BEGIN SELECT RAISE(ABORT,'review task linkage mismatch'); END")
        op.execute("CREATE TRIGGER enforce_review_task_linkage_update BEFORE UPDATE ON review_tasks WHEN NEW.root_id!=OLD.root_id OR NEW.project_id!=OLD.project_id BEGIN SELECT RAISE(ABORT,'review task linkage immutable'); END")
        op.execute("CREATE TRIGGER enforce_review_task_state BEFORE UPDATE ON review_tasks WHEN NOT ((OLD.status='pending' AND NEW.status='claimed' AND NEW.lease_version=OLD.lease_version+1 AND NEW.lease_expires_at>CURRENT_TIMESTAMP) OR (OLD.status='claimed' AND NEW.status='claimed' AND NEW.lease_version=OLD.lease_version+1 AND ((NEW.reviewer_id=OLD.reviewer_id AND OLD.lease_expires_at>CURRENT_TIMESTAMP AND NEW.lease_expires_at>OLD.lease_expires_at) OR (OLD.lease_expires_at<=CURRENT_TIMESTAMP AND NEW.lease_expires_at>CURRENT_TIMESTAMP))) OR (OLD.status='claimed' AND NEW.status='pending' AND NEW.lease_version=OLD.lease_version+1) OR (OLD.status='claimed' AND OLD.lease_expires_at>CURRENT_TIMESTAMP AND NEW.status='completed' AND NEW.lease_version=OLD.lease_version+1 AND NEW.reviewer_id=OLD.reviewer_id AND EXISTS(SELECT 1 FROM fact_versions v WHERE v.review_task_id=OLD.id AND v.review_lease_version=OLD.lease_version AND v.actor_id=OLD.reviewer_id AND v.root_id=OLD.root_id))) BEGIN SELECT RAISE(ABORT,'review task state mismatch'); END")
        op.execute("CREATE TRIGGER enforce_review_task_insert BEFORE INSERT ON review_tasks WHEN NEW.status!='pending' OR NEW.lease_version!=0 OR NEW.reviewer_id IS NOT NULL OR NEW.lease_expires_at IS NOT NULL BEGIN SELECT RAISE(ABORT,'review task initial state mismatch'); END")
        op.execute("CREATE TRIGGER prevent_review_task_delete BEFORE DELETE ON review_tasks BEGIN SELECT RAISE(ABORT,'review tasks immutable'); END")
    elif dialect=="postgresql":
        op.execute("CREATE FUNCTION enforce_review_root_linkage() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF (NEW.source='raw' AND NOT EXISTS(SELECT 1 FROM raw_facts f WHERE f.id=NEW.raw_fact_id AND f.project_id=NEW.project_id AND f.document_id=NEW.document_id AND f.document_version_id=NEW.document_version_id)) OR (NEW.document_version_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM document_versions v JOIN documents d ON d.id=v.document_id WHERE v.id=NEW.document_version_id AND d.id=NEW.document_id AND d.project_id=NEW.project_id)) OR (NEW.document_version_id IS NULL AND NEW.document_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM documents d WHERE d.id=NEW.document_id AND d.project_id=NEW.project_id)) THEN RAISE EXCEPTION 'review root linkage mismatch';END IF;RETURN NEW;END $$")
        op.execute("CREATE TRIGGER enforce_review_root_linkage BEFORE INSERT ON review_fact_roots FOR EACH ROW EXECUTE FUNCTION enforce_review_root_linkage()")
        op.execute("CREATE FUNCTION enforce_fact_version_linkage() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE n integer;BEGIN PERFORM pg_advisory_xact_lock(hashtextextended(NEW.root_id::text,0));SELECT COALESCE(MAX(version_number),0) INTO n FROM fact_versions WHERE root_id=NEW.root_id;IF NEW.version_number<>n+1 OR NOT EXISTS(SELECT 1 FROM review_fact_roots r WHERE r.id=NEW.root_id AND r.project_id=NEW.project_id) THEN RAISE EXCEPTION 'fact version linkage mismatch';END IF;RETURN NEW;END $$")
        op.execute("CREATE TRIGGER enforce_fact_version_linkage BEFORE INSERT ON fact_versions FOR EACH ROW EXECUTE FUNCTION enforce_fact_version_linkage()")
        op.execute("CREATE FUNCTION enforce_fact_version_task() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF (NEW.action!='manual_create' AND NOT EXISTS(SELECT 1 FROM review_tasks t WHERE t.id=NEW.review_task_id AND t.root_id=NEW.root_id AND t.project_id=NEW.project_id AND t.reviewer_id=NEW.actor_id AND t.status='claimed' AND t.lease_version=NEW.review_lease_version AND t.lease_expires_at>CURRENT_TIMESTAMP)) OR (NEW.action='manual_create' AND NOT EXISTS(SELECT 1 FROM review_fact_roots r WHERE r.id=NEW.root_id AND r.source='manual' AND r.created_by_id=NEW.actor_id AND NEW.version_number=1 AND NEW.review_task_id IS NULL AND NEW.review_lease_version IS NULL)) THEN RAISE EXCEPTION 'fact version task mismatch';END IF;RETURN NEW;END $$")
        op.execute("CREATE TRIGGER enforce_fact_version_task BEFORE INSERT ON fact_versions FOR EACH ROW EXECUTE FUNCTION enforce_fact_version_task()")
        op.execute("CREATE FUNCTION prevent_review_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'review history immutable';END $$")
        op.execute("CREATE TRIGGER prevent_fact_version_mutation BEFORE UPDATE OR DELETE ON fact_versions FOR EACH ROW EXECUTE FUNCTION prevent_review_history_mutation()")
        op.execute("CREATE TRIGGER prevent_review_root_mutation BEFORE UPDATE OR DELETE ON review_fact_roots FOR EACH ROW EXECUTE FUNCTION prevent_review_history_mutation()")
        op.execute("CREATE TRIGGER prevent_review_task_delete BEFORE DELETE ON review_tasks FOR EACH ROW EXECUTE FUNCTION prevent_review_history_mutation()")
        op.execute("CREATE FUNCTION enforce_review_task_linkage() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF (TG_OP='INSERT' AND (NEW.status!='pending' OR NEW.lease_version!=0 OR NEW.reviewer_id IS NOT NULL OR NEW.lease_expires_at IS NOT NULL)) OR (TG_OP='UPDATE' AND ((NEW.root_id<>OLD.root_id OR NEW.project_id<>OLD.project_id) OR NOT ((OLD.status='pending' AND NEW.status='claimed' AND NEW.lease_version=OLD.lease_version+1 AND NEW.lease_expires_at>CURRENT_TIMESTAMP) OR (OLD.status='claimed' AND NEW.status='claimed' AND NEW.lease_version=OLD.lease_version+1 AND ((NEW.reviewer_id=OLD.reviewer_id AND OLD.lease_expires_at>CURRENT_TIMESTAMP AND NEW.lease_expires_at>OLD.lease_expires_at) OR (OLD.lease_expires_at<=CURRENT_TIMESTAMP AND NEW.lease_expires_at>CURRENT_TIMESTAMP))) OR (OLD.status='claimed' AND NEW.status='pending' AND NEW.lease_version=OLD.lease_version+1) OR (OLD.status='claimed' AND OLD.lease_expires_at>CURRENT_TIMESTAMP AND NEW.status='completed' AND NEW.lease_version=OLD.lease_version+1 AND NEW.reviewer_id=OLD.reviewer_id AND EXISTS(SELECT 1 FROM fact_versions v WHERE v.review_task_id=OLD.id AND v.review_lease_version=OLD.lease_version AND v.actor_id=OLD.reviewer_id AND v.root_id=OLD.root_id))))) OR NOT EXISTS(SELECT 1 FROM review_fact_roots r WHERE r.id=NEW.root_id AND r.project_id=NEW.project_id) THEN RAISE EXCEPTION 'review task linkage mismatch';END IF;RETURN NEW;END $$")
        op.execute("CREATE TRIGGER enforce_review_task_linkage BEFORE INSERT OR UPDATE ON review_tasks FOR EACH ROW EXECUTE FUNCTION enforce_review_task_linkage()")


def downgrade() -> None:
    dialect=op.get_bind().dialect.name
    if dialect=="sqlite":
        for n in ("prevent_review_task_delete","enforce_review_task_insert","enforce_review_task_state","enforce_review_task_linkage_update","enforce_review_task_linkage_insert","enforce_fact_version_task","enforce_fact_version_linkage","enforce_review_root_linkage","prevent_fact_versions_delete","prevent_fact_versions_update","prevent_review_fact_roots_delete","prevent_review_fact_roots_update"):op.execute(f"DROP TRIGGER IF EXISTS {n}")
    elif dialect=="postgresql":
        op.execute("DROP TRIGGER IF EXISTS enforce_review_task_linkage ON review_tasks");op.execute("DROP FUNCTION IF EXISTS enforce_review_task_linkage()");op.execute("DROP TRIGGER IF EXISTS prevent_review_task_delete ON review_tasks");op.execute("DROP TRIGGER IF EXISTS prevent_review_root_mutation ON review_fact_roots");op.execute("DROP TRIGGER IF EXISTS prevent_fact_version_mutation ON fact_versions");op.execute("DROP FUNCTION IF EXISTS prevent_review_history_mutation()");op.execute("DROP TRIGGER IF EXISTS enforce_fact_version_task ON fact_versions");op.execute("DROP FUNCTION IF EXISTS enforce_fact_version_task()");op.execute("DROP TRIGGER IF EXISTS enforce_fact_version_linkage ON fact_versions");op.execute("DROP FUNCTION IF EXISTS enforce_fact_version_linkage()");op.execute("DROP TRIGGER IF EXISTS enforce_review_root_linkage ON review_fact_roots");op.execute("DROP FUNCTION IF EXISTS enforce_review_root_linkage()")
    op.drop_index("ix_fact_versions_review_task_id",table_name="fact_versions")
    for c in reversed(("root_id","project_id","actor_id","action","is_tombstone","is_published")):op.drop_index(f"ix_fact_versions_{c}",table_name="fact_versions")
    op.drop_table("fact_versions")
    op.drop_index("uq_review_task_active_root",table_name="review_tasks")
    for c in reversed(("project_id","root_id","reviewer_id","lease_expires_at","status")):op.drop_index(f"ix_review_tasks_{c}",table_name="review_tasks")
    op.drop_table("review_tasks");op.drop_index("ix_review_fact_roots_raw_fact_id",table_name="review_fact_roots");op.drop_index("ix_review_fact_roots_project_id",table_name="review_fact_roots");op.drop_table("review_fact_roots")
