"""audited immutable project exports and snapshot items"""
from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa

revision: str = "0010_exports_audit"
down_revision: str | None = "0009_reviews"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _common(): return [sa.Column("id",sa.Uuid(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),nullable=False)]


def upgrade() -> None:
    op.create_table("exports",*_common(),
        sa.Column("project_id",sa.Uuid(),nullable=False),sa.Column("actor_id",sa.Uuid(),nullable=False),
        sa.Column("filters_json",sa.JSON(),nullable=False),sa.Column("format",sa.String(8),nullable=False),
        sa.Column("include_unreviewed",sa.Boolean(),nullable=False),sa.Column("record_count",sa.Integer(),nullable=False),
        sa.Column("size_bytes",sa.BigInteger(),nullable=False),sa.Column("sha256",sa.String(64)),
        sa.Column("storage_key",sa.String(128),nullable=False),
        sa.Column("owner_token",sa.String(32),nullable=False),sa.Column("status",sa.String(16),nullable=False),
        sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("cleanup_token",sa.String(32)),
        sa.Column("cleanup_claimed_at",sa.DateTime(timezone=True)),sa.Column("idempotency_key",sa.String(128),nullable=False),
        sa.Column("request_fingerprint",sa.String(64),nullable=False),
        sa.CheckConstraint("format IN ('tsv','csv','json')",name="ck_export_format"),
        sa.CheckConstraint("status IN ('pending','cleanup_claimed','completed')",name="ck_export_status"),
        sa.CheckConstraint("record_count>=0 AND size_bytes>=0",name="ck_export_sizes"),
        sa.CheckConstraint("length(owner_token)=32 AND length(request_fingerprint)=64",name="ck_export_identity"),
        sa.CheckConstraint("length(idempotency_key) BETWEEN 1 AND 128",name="ck_export_idempotency"),
        sa.CheckConstraint("(status='pending' AND completed_at IS NULL AND sha256 IS NULL AND cleanup_token IS NULL AND cleanup_claimed_at IS NULL) OR (status='cleanup_claimed' AND completed_at IS NULL AND sha256 IS NULL AND length(cleanup_token)=32 AND cleanup_claimed_at IS NOT NULL) OR (status='completed' AND completed_at IS NOT NULL AND length(sha256)=64 AND cleanup_token IS NULL AND cleanup_claimed_at IS NULL)",name="ck_export_completion"),
        sa.ForeignKeyConstraint(["project_id"],["projects.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["actor_id"],["users.id"],ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("project_id","actor_id","idempotency_key",name="uq_export_actor_request"),sa.UniqueConstraint("storage_key",name="uq_export_storage_key"))
    op.create_index("ix_exports_project_id","exports",["project_id"]);op.create_index("ix_exports_actor_id","exports",["actor_id"]);op.create_index("ix_exports_cleanup_claimed_at","exports",["cleanup_claimed_at"])
    op.create_table("export_items",*_common(),sa.Column("export_id",sa.Uuid(),nullable=False),sa.Column("ordinal",sa.Integer(),nullable=False),
        sa.Column("project_id",sa.Uuid(),nullable=False),sa.Column("source_kind",sa.String(8),nullable=False),
        sa.Column("fact_version_id",sa.Uuid()),sa.Column("raw_fact_id",sa.Uuid()),
        sa.CheckConstraint("ordinal>=0",name="ck_export_item_ordinal"),sa.CheckConstraint("source_kind IN ('version','raw')",name="ck_export_item_source"),
        sa.CheckConstraint("(source_kind='version' AND fact_version_id IS NOT NULL AND raw_fact_id IS NULL) OR (source_kind='raw' AND raw_fact_id IS NOT NULL AND fact_version_id IS NULL)",name="ck_export_item_xor"),
        sa.ForeignKeyConstraint(["export_id"],["exports.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["project_id"],["projects.id"],ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["fact_version_id"],["fact_versions.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["raw_fact_id"],["raw_facts.id"],ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("export_id","ordinal",name="uq_export_item_ordinal"),
        sa.UniqueConstraint("export_id","fact_version_id",name="uq_export_item_version"),sa.UniqueConstraint("export_id","raw_fact_id",name="uq_export_item_raw"))
    for c in ("export_id","project_id","fact_version_id","raw_fact_id"):op.create_index(f"ix_export_items_{c}","export_items",[c])
    op.create_table("audit_events",*_common(),sa.Column("actor_id",sa.Uuid(),nullable=False),sa.Column("project_id",sa.Uuid()),sa.Column("action",sa.String(100),nullable=False),sa.Column("target_type",sa.String(50),nullable=False),sa.Column("target_id",sa.Uuid()),sa.Column("request_id",sa.String(128),nullable=False),sa.Column("outcome",sa.String(16),nullable=False),sa.Column("metadata_json",sa.JSON(),nullable=False),
        sa.CheckConstraint("length(action) BETWEEN 1 AND 100 AND outcome IN ('requested','success','failure','denied')",name="ck_audit_base"),sa.CheckConstraint("length(request_id) BETWEEN 1 AND 128",name="ck_audit_request_id"),sa.ForeignKeyConstraint(["actor_id"],["users.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["project_id"],["projects.id"],ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id"))
    for c in ("actor_id","project_id","action","target_id","request_id","outcome"):op.create_index(f"ix_audit_events_{c}","audit_events",[c])
    d=op.get_bind().dialect.name
    if d=="sqlite":
        op.execute("CREATE TRIGGER enforce_export_linkage BEFORE INSERT ON exports WHEN NEW.status!='pending' OR (NOT EXISTS(SELECT 1 FROM project_memberships m WHERE m.project_id=NEW.project_id AND m.user_id=NEW.actor_id) AND NOT EXISTS(SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=NEW.actor_id AND r.name='admin')) BEGIN SELECT RAISE(ABORT,'export linkage mismatch'); END")
        op.execute("CREATE TRIGGER enforce_export_item_linkage BEFORE INSERT ON export_items WHEN NOT EXISTS(SELECT 1 FROM exports e WHERE e.id=NEW.export_id AND e.project_id=NEW.project_id AND e.status='pending') OR (NEW.source_kind='version' AND NOT EXISTS(SELECT 1 FROM fact_versions v WHERE v.id=NEW.fact_version_id AND v.project_id=NEW.project_id)) OR (NEW.source_kind='raw' AND NOT EXISTS(SELECT 1 FROM raw_facts r WHERE r.id=NEW.raw_fact_id AND r.project_id=NEW.project_id)) BEGIN SELECT RAISE(ABORT,'export item linkage mismatch'); END")
        op.execute("CREATE TRIGGER enforce_export_completion BEFORE UPDATE ON exports WHEN NOT ((OLD.status='pending' AND NEW.status='completed' AND NEW.id=OLD.id AND NEW.created_at=OLD.created_at AND NEW.project_id=OLD.project_id AND NEW.actor_id=OLD.actor_id AND NEW.filters_json=OLD.filters_json AND NEW.format=OLD.format AND NEW.include_unreviewed=OLD.include_unreviewed AND NEW.storage_key=OLD.storage_key AND NEW.owner_token=OLD.owner_token AND NEW.idempotency_key=OLD.idempotency_key AND NEW.request_fingerprint=OLD.request_fingerprint AND NEW.completed_at IS NOT NULL AND length(NEW.sha256)=64 AND NEW.cleanup_token IS NULL AND NEW.cleanup_claimed_at IS NULL AND (SELECT count(*) FROM export_items i WHERE i.export_id=NEW.id)=NEW.record_count AND (NEW.record_count=0 OR ((SELECT min(ordinal) FROM export_items i WHERE i.export_id=NEW.id)=0 AND (SELECT max(ordinal) FROM export_items i WHERE i.export_id=NEW.id)=NEW.record_count-1))) OR (OLD.status IN ('pending','cleanup_claimed') AND NEW.status='cleanup_claimed' AND NEW.id=OLD.id AND NEW.created_at=OLD.created_at AND NEW.project_id=OLD.project_id AND NEW.actor_id=OLD.actor_id AND NEW.filters_json=OLD.filters_json AND NEW.format=OLD.format AND NEW.include_unreviewed=OLD.include_unreviewed AND NEW.record_count=OLD.record_count AND NEW.size_bytes=OLD.size_bytes AND NEW.sha256 IS OLD.sha256 AND NEW.completed_at IS OLD.completed_at AND NEW.storage_key=OLD.storage_key AND NEW.owner_token=OLD.owner_token AND NEW.idempotency_key=OLD.idempotency_key AND NEW.request_fingerprint=OLD.request_fingerprint AND length(NEW.cleanup_token)=32 AND NEW.cleanup_claimed_at IS NOT NULL AND (OLD.status='pending' OR NEW.cleanup_token!=OLD.cleanup_token OR NEW.cleanup_claimed_at>=OLD.cleanup_claimed_at))) BEGIN SELECT RAISE(ABORT,'export completion mismatch'); END")
        op.execute("CREATE TRIGGER enforce_export_audit_combo BEFORE INSERT ON audit_events WHEN NEW.action LIKE 'export.%' AND NOT ((NEW.action='export.request' AND NEW.outcome='requested' AND NEW.target_id IS NULL) OR (NEW.action='export.success' AND NEW.outcome='success' AND NEW.target_id IS NOT NULL) OR (NEW.action='export.failure' AND NEW.outcome='failure' AND NEW.target_id IS NULL) OR (NEW.action='export.denied' AND NEW.outcome='denied' AND NEW.target_id IS NULL) OR (NEW.action='export.download' AND NEW.outcome IN ('success','failure') AND NEW.target_id IS NOT NULL)) BEGIN SELECT RAISE(ABORT,'audit event action mismatch'); END")
        op.execute("CREATE TRIGGER enforce_audit_event_target BEFORE INSERT ON audit_events WHEN ((NEW.action='export.success' OR (NEW.action='export.download' AND NEW.outcome='success')) AND NOT EXISTS(SELECT 1 FROM exports e WHERE e.id=NEW.target_id AND e.project_id=NEW.project_id AND e.status='completed')) OR (NEW.action='export.download' AND NEW.outcome='failure' AND NOT EXISTS(SELECT 1 FROM exports e WHERE e.id=NEW.target_id AND e.project_id=NEW.project_id)) BEGIN SELECT RAISE(ABORT,'audit event target mismatch'); END")
        op.execute("CREATE TRIGGER prevent_export_items_update BEFORE UPDATE ON export_items BEGIN SELECT RAISE(ABORT,'history immutable'); END");op.execute("CREATE TRIGGER prevent_export_items_delete BEFORE DELETE ON export_items WHEN EXISTS(SELECT 1 FROM exports e WHERE e.id=OLD.export_id AND e.status='completed') BEGIN SELECT RAISE(ABORT,'history immutable'); END")
        for a in ("update","delete"):op.execute(f"CREATE TRIGGER prevent_audit_events_{a} BEFORE {a.upper()} ON audit_events BEGIN SELECT RAISE(ABORT,'history immutable'); END")
        op.execute("CREATE TRIGGER prevent_export_delete BEFORE DELETE ON exports WHEN OLD.status!='cleanup_claimed' BEGIN SELECT RAISE(ABORT,'export history immutable'); END")
    elif d=="postgresql":
        op.execute("CREATE FUNCTION enforce_export_insert() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.status!='pending' OR (NOT EXISTS(SELECT 1 FROM project_memberships m WHERE m.project_id=NEW.project_id AND m.user_id=NEW.actor_id) AND NOT EXISTS(SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=NEW.actor_id AND r.name='admin')) THEN RAISE EXCEPTION 'export linkage mismatch';END IF;RETURN NEW;END $$")
        op.execute("CREATE TRIGGER enforce_export_linkage BEFORE INSERT ON exports FOR EACH ROW EXECUTE FUNCTION enforce_export_insert()")
        op.execute("CREATE FUNCTION enforce_export_item() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM exports e WHERE e.id=NEW.export_id AND e.project_id=NEW.project_id AND e.status='pending') OR (NEW.source_kind='version' AND NOT EXISTS(SELECT 1 FROM fact_versions v WHERE v.id=NEW.fact_version_id AND v.project_id=NEW.project_id)) OR (NEW.source_kind='raw' AND NOT EXISTS(SELECT 1 FROM raw_facts r WHERE r.id=NEW.raw_fact_id AND r.project_id=NEW.project_id)) THEN RAISE EXCEPTION 'export item linkage mismatch';END IF;RETURN NEW;END $$")
        op.execute("CREATE TRIGGER enforce_export_item_linkage BEFORE INSERT ON export_items FOR EACH ROW EXECUTE FUNCTION enforce_export_item()")
        op.execute("CREATE FUNCTION enforce_export_completion() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NOT ((OLD.status='pending' AND NEW.status='completed' AND NEW.id=OLD.id AND NEW.created_at=OLD.created_at AND NEW.project_id=OLD.project_id AND NEW.actor_id=OLD.actor_id AND NEW.filters_json=OLD.filters_json AND NEW.format=OLD.format AND NEW.include_unreviewed=OLD.include_unreviewed AND NEW.storage_key=OLD.storage_key AND NEW.owner_token=OLD.owner_token AND NEW.idempotency_key=OLD.idempotency_key AND NEW.request_fingerprint=OLD.request_fingerprint AND NEW.completed_at IS NOT NULL AND length(NEW.sha256)=64 AND NEW.cleanup_token IS NULL AND NEW.cleanup_claimed_at IS NULL AND (SELECT count(*) FROM export_items i WHERE i.export_id=NEW.id)=NEW.record_count AND (NEW.record_count=0 OR ((SELECT min(ordinal) FROM export_items i WHERE i.export_id=NEW.id)=0 AND (SELECT max(ordinal) FROM export_items i WHERE i.export_id=NEW.id)=NEW.record_count-1))) OR (OLD.status IN ('pending','cleanup_claimed') AND NEW.status='cleanup_claimed' AND NEW.id=OLD.id AND NEW.created_at=OLD.created_at AND NEW.project_id=OLD.project_id AND NEW.actor_id=OLD.actor_id AND NEW.filters_json=OLD.filters_json AND NEW.format=OLD.format AND NEW.include_unreviewed=OLD.include_unreviewed AND NEW.record_count=OLD.record_count AND NEW.size_bytes=OLD.size_bytes AND NEW.sha256 IS NOT DISTINCT FROM OLD.sha256 AND NEW.completed_at IS NOT DISTINCT FROM OLD.completed_at AND NEW.storage_key=OLD.storage_key AND NEW.owner_token=OLD.owner_token AND NEW.idempotency_key=OLD.idempotency_key AND NEW.request_fingerprint=OLD.request_fingerprint AND length(NEW.cleanup_token)=32 AND NEW.cleanup_claimed_at IS NOT NULL AND (OLD.status='pending' OR NEW.cleanup_token!=OLD.cleanup_token OR NEW.cleanup_claimed_at>=OLD.cleanup_claimed_at))) THEN RAISE EXCEPTION 'export completion mismatch';END IF;RETURN NEW;END $$")
        op.execute("CREATE TRIGGER enforce_export_completion BEFORE UPDATE ON exports FOR EACH ROW EXECUTE FUNCTION enforce_export_completion()")
        op.execute("CREATE FUNCTION enforce_audit_target() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action LIKE 'export.%' AND NOT ((NEW.action='export.request' AND NEW.outcome='requested' AND NEW.target_id IS NULL) OR (NEW.action='export.success' AND NEW.outcome='success' AND NEW.target_id IS NOT NULL) OR (NEW.action='export.failure' AND NEW.outcome='failure' AND NEW.target_id IS NULL) OR (NEW.action='export.denied' AND NEW.outcome='denied' AND NEW.target_id IS NULL) OR (NEW.action='export.download' AND NEW.outcome IN ('success','failure') AND NEW.target_id IS NOT NULL)) OR ((NEW.action='export.success' OR (NEW.action='export.download' AND NEW.outcome='success')) AND NOT EXISTS(SELECT 1 FROM exports e WHERE e.id=NEW.target_id AND e.project_id=NEW.project_id AND e.status='completed')) OR (NEW.action='export.download' AND NEW.outcome='failure' AND NOT EXISTS(SELECT 1 FROM exports e WHERE e.id=NEW.target_id AND e.project_id=NEW.project_id)) THEN RAISE EXCEPTION 'audit event target mismatch';END IF;RETURN NEW;END $$")
        op.execute("CREATE TRIGGER enforce_audit_event_target BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION enforce_audit_target()")
        op.execute("CREATE FUNCTION prevent_export_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'export history immutable';END $$")
        op.execute("CREATE TRIGGER prevent_export_delete BEFORE DELETE ON exports FOR EACH ROW WHEN (OLD.status!='cleanup_claimed') EXECUTE FUNCTION prevent_export_history_mutation()")
        op.execute("CREATE FUNCTION prevent_export_item_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_OP='UPDATE' OR EXISTS(SELECT 1 FROM exports e WHERE e.id=OLD.export_id AND e.status='completed') THEN RAISE EXCEPTION 'export items immutable';END IF;RETURN OLD;END $$")
        op.execute("CREATE TRIGGER prevent_export_item_update BEFORE UPDATE ON export_items FOR EACH ROW EXECUTE FUNCTION prevent_export_item_mutation()")
        op.execute("CREATE TRIGGER prevent_export_item_delete BEFORE DELETE ON export_items FOR EACH ROW EXECUTE FUNCTION prevent_export_item_mutation()")
        op.execute("CREATE TRIGGER prevent_audit_event_mutation BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION prevent_export_history_mutation()")


def downgrade() -> None:
    if op.get_bind().dialect.name=="postgresql":
        for t,n in (("audit_events","prevent_audit_event_mutation"),("export_items","prevent_export_item_delete"),("export_items","prevent_export_item_update"),("exports","prevent_export_delete"),("audit_events","enforce_audit_event_target"),("exports","enforce_export_completion"),("export_items","enforce_export_item_linkage"),("exports","enforce_export_linkage")):op.execute(f"DROP TRIGGER IF EXISTS {n} ON {t}")
        for f in ("prevent_export_item_mutation","prevent_export_history_mutation","enforce_audit_target","enforce_export_completion","enforce_export_item","enforce_export_insert"):op.execute(f"DROP FUNCTION IF EXISTS {f}()")
    for c in reversed(("actor_id","project_id","action","target_id","request_id","outcome")):op.drop_index(f"ix_audit_events_{c}",table_name="audit_events")
    op.drop_table("audit_events")
    for c in reversed(("export_id","project_id","fact_version_id","raw_fact_id")):op.drop_index(f"ix_export_items_{c}",table_name="export_items")
    op.drop_table("export_items");op.drop_index("ix_exports_cleanup_claimed_at",table_name="exports");op.drop_index("ix_exports_actor_id",table_name="exports");op.drop_index("ix_exports_project_id",table_name="exports");op.drop_table("exports")
