<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'
import { createUser, disableUser, listUsers, updateUser, type AdminUser } from '../api/admin'
import { addProjectMember, listProjectMembers, listProjects, removeProjectMember, updateProjectMember, type Project, type ProjectMember } from '../api/projects'
import { createModel, deleteModel, listAdminModels, updateModel, type AdminModel } from '../api/models'

type Dialog = 'user' | 'member' | 'model' | null
const props = withDefaults(defineProps<{ authorized?: boolean }>(), { authorized: true })
const route = useRoute()
const section = computed(() => ['users', 'members', 'models'].includes(String(route.query.section)) ? String(route.query.section) : 'users')
const users = ref<AdminUser[]>([]); const projects = ref<Project[]>([]); const models = ref<AdminModel[]>([]); const members = ref<ProjectMember[]>([])
const selectedProjectId = ref(''); const selectedModelId = ref(''); const dialog = ref<Dialog>(null); const editingUser = ref<AdminUser | null>(null)
const editingModel = ref<AdminModel | null>(null)
const username = ref(''); const password = ref(''); const role = ref('viewer'); const projectIds = ref<string[]>([]); const memberUser = ref(''); const memberRole = ref<'owner' | 'member'>('member')
const configName = ref(''); const endpoint = ref(''); const host = ref(''); const modelName = ref(''); const apiKey = ref('')
const message = ref(''); const error = ref('')

function clearFeedback() { message.value = ''; error.value = '' }
function closeDialog() { dialog.value = null; password.value = ''; apiKey.value = ''; projectIds.value = []; editingUser.value = null; editingModel.value = null }
function openUser(user?: AdminUser) { clearFeedback(); editingUser.value = user ?? null; username.value = user?.username ?? ''; password.value = ''; role.value = user?.roles[0] ?? 'viewer'; projectIds.value = user ? [] : projects.value.map((project) => project.id); dialog.value = 'user' }
function openMember() { clearFeedback(); memberUser.value = users.value.find((user) => !user.is_disabled)?.id ?? ''; memberRole.value = 'member'; dialog.value = 'member' }
function openModel(model?: AdminModel) { clearFeedback(); editingModel.value = model ?? null; configName.value = model?.name ?? '阿里云百炼'; endpoint.value = model?.endpoint ?? 'https://dashscope.aliyuncs.com/compatible-mode/v1'; host.value = model?.allowed_hosts.join(', ') ?? 'dashscope.aliyuncs.com'; modelName.value = model?.model_name ?? 'qwen-plus'; apiKey.value = ''; dialog.value = 'model' }
async function loadMembers() { members.value = selectedProjectId.value ? await listProjectMembers(selectedProjectId.value) : [] }
async function load() {
  const [userValues, projectValues, modelValues] = await Promise.all([listUsers(), listProjects(), listAdminModels()])
  users.value = userValues; projects.value = projectValues; models.value = modelValues
  selectedProjectId.value = selectedProjectId.value || projects.value[0]?.id || ''; selectedModelId.value = models.value[0]?.id || ''
  await loadMembers()
}
async function saveUser() {
  try { if (editingUser.value) await updateUser(editingUser.value.id, { username: username.value.trim(), roles: [role.value], ...(password.value ? { password: password.value } : {}) }); else await createUser(username.value.trim(), password.value, [role.value], projectIds.value); message.value = editingUser.value ? '账号已更新' : '本地账号已创建'; closeDialog(); await load() }
  catch { error.value = '账号未能保存，请检查用户名与角色' } finally { password.value = '' }
}
async function disable(user: AdminUser) { if (!confirm(`停用账号“${user.username}”？`)) return; try { await disableUser(user.id); message.value = '账号已停用'; await load() } catch { error.value = '账号未能停用' } }
async function saveMember() { try { await addProjectMember(selectedProjectId.value, memberUser.value, memberRole.value); message.value = '项目成员已添加'; closeDialog(); await loadMembers() } catch { error.value = '成员未能保存' } }
async function changeRole(member: ProjectMember) { const role = member.role === 'owner' ? 'member' : 'owner'; try { await updateProjectMember(selectedProjectId.value, member.id, role); await loadMembers() } catch { error.value = '成员角色未能更新' } }
async function removeMember(member: ProjectMember) { if (!confirm(`移除成员“${member.username}”？`)) return; try { await removeProjectMember(selectedProjectId.value, member.id); message.value = '成员已移除'; await loadMembers() } catch { error.value = '成员未能移除，项目必须保留负责人' } }
async function saveModel() { try { const payload = { name: configName.value, endpoint: endpoint.value, model_name: modelName.value, allowed_hosts: host.value.split(',').map((item) => item.trim()).filter(Boolean) }; const model = editingModel.value ? await updateModel(editingModel.value.id, payload) : await createModel({ ...payload, provider: 'openai-compatible', api_key: apiKey.value, allow_private_network: false, allow_insecure_http: false, provider_supports_idempotency: true, is_enabled: true }); selectedModelId.value = model.id; message.value = editingModel.value ? '模型配置已更新' : '模型配置已加密保存'; closeDialog(); await load() } catch { error.value = '模型配置未能保存' } finally { apiKey.value = '' } }
async function toggleModel(model: AdminModel) { try { await updateModel(model.id, { is_enabled: !model.is_enabled }); message.value = model.is_enabled ? '模型已停用' : '模型已启用'; await load() } catch { error.value = '模型状态未能更新' } }
async function removeModel(model: AdminModel) { if (!confirm(`删除模型配置“${model.name}”？`)) return; try { await deleteModel(model.id); message.value = '模型配置已删除'; await load() } catch { error.value = '模型已有历史调用记录，不能删除；请改为停用' } }
if (props.authorized) void load().catch(() => { error.value = '管理数据暂时无法载入' })
</script>

<template><section aria-labelledby="admin-title" class="admin-page"><p class="eyebrow">仅管理员</p><h1 id="admin-title">系统管理</h1><p v-if="!authorized" class="message error">您没有系统管理权限。</p><template v-else><p v-if="message" class="message success">{{ message }}</p><p v-if="error" class="message error">{{ error }}</p>
  <section v-if="section === 'users'" class="management-section"><header class="management-head"><div><h2>用户管理</h2><p>管理本地账号、角色与使用状态。</p></div><button class="primary" type="button" @click="openUser()">新增用户</button></header><div class="model-table-wrap"><table><thead><tr><th>用户名</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td><strong>{{ user.username }}</strong></td><td>{{ user.roles.join('、') }}</td><td><span class="status" :class="user.is_disabled ? 'status--cancelled' : 'status--completed'">{{ user.is_disabled ? '已停用' : '正常' }}</span></td><td class="row-actions"><button type="button" @click="openUser(user)">编辑</button><button type="button" :disabled="user.is_disabled" @click="disable(user)">停用</button></td></tr><tr v-if="!users.length"><td class="model-empty" colspan="4">暂无用户。</td></tr></tbody></table></div></section>
  <section v-else-if="section === 'members'" class="management-section"><header class="management-head"><div><h2>项目成员</h2><p>为项目分配成员与负责人。</p></div><div class="head-actions"><label>项目<select v-model="selectedProjectId" @change="loadMembers"><option v-for="project in projects" :key="project.id" :value="project.id">{{ project.name }}</option></select></label><button class="primary" type="button" :disabled="!selectedProjectId" @click="openMember">添加成员</button></div></header><div class="model-table-wrap"><table><thead><tr><th>用户</th><th>角色</th><th>操作</th></tr></thead><tbody><tr v-for="member in members" :key="member.id"><td><strong>{{ member.username }}</strong></td><td><span class="status" :class="member.role === 'owner' ? 'status--running' : 'status--queued'">{{ member.role === 'owner' ? '负责人' : '成员' }}</span></td><td class="row-actions"><button type="button" @click="changeRole(member)">设为{{ member.role === 'owner' ? '成员' : '负责人' }}</button><button type="button" @click="removeMember(member)">移除</button></td></tr><tr v-if="!members.length"><td class="model-empty" colspan="3">此项目暂无成员。</td></tr></tbody></table></div></section>
  <section v-else class="management-section"><header class="management-head"><div><h2>模型配置</h2><p>集中管理模型服务、接口地址与启用状态。</p></div><button class="primary" type="button" @click="openModel()">新增配置</button></header><div class="model-table-wrap"><table><thead><tr><th>配置名称</th><th>提供商</th><th>模型名称</th><th>Base URL</th><th>允许主机</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="model in models" :key="model.id"><td><strong>{{ model.name }}</strong></td><td>{{ model.provider }}</td><td>{{ model.model_name }}</td><td class="model-endpoint">{{ model.endpoint }}</td><td>{{ model.allowed_hosts.join('、') }}</td><td><span class="status" :class="model.is_enabled ? 'status--completed' : 'status--cancelled'">{{ model.is_enabled ? '已启用' : '已停用' }}</span></td><td class="row-actions"><button type="button" @click="openModel(model)">编辑</button><button type="button" @click="toggleModel(model)">{{ model.is_enabled ? '停用' : '启用' }}</button><button type="button" @click="removeModel(model)">删除</button></td></tr><tr v-if="!models.length"><td class="model-empty" colspan="7">暂无模型配置。</td></tr></tbody></table></div></section></template></section>
  <div v-if="dialog" class="dialog-backdrop" @click.self="closeDialog"><form class="model-dialog" @submit.prevent="dialog === 'user' ? saveUser() : dialog === 'member' ? saveMember() : saveModel()"><header><h2>{{ dialog === 'user' ? (editingUser ? '编辑用户' : '新增用户') : dialog === 'member' ? '添加项目成员' : '新增模型配置' }}</h2><button class="dialog-close" type="button" aria-label="关闭" @click="closeDialog">×</button></header><div class="model-dialog__fields" v-if="dialog === 'user'"><label>用户名<input v-model="username" required /></label><label>角色<select v-model="role"><option value="viewer">查看者</option><option value="operator">抽取操作员</option><option value="reviewer">评审员</option><option value="admin">管理员</option></select></label><fieldset v-if="!editingUser" class="field-span"><legend>可访问项目</legend><label v-for="project in projects" :key="project.id" class="check-row"><input v-model="projectIds" type="checkbox" :value="project.id" />{{ project.name }}</label><p v-if="!projects.length" class="muted">当前没有可分配的项目。</p></fieldset><label class="field-span">{{ editingUser ? '重设密码（留空则不修改）' : '初始密码' }}<input v-model="password" type="password" minlength="12" :required="!editingUser" /></label></div><div class="model-dialog__fields" v-else-if="dialog === 'member'"><label>用户<select v-model="memberUser"><option v-for="user in users.filter((item) => !item.is_disabled)" :key="user.id" :value="user.id">{{ user.username }}</option></select></label><label>项目角色<select v-model="memberRole"><option value="member">成员</option><option value="owner">负责人</option></select></label></div><div class="model-dialog__fields" v-else><label>配置名称<input v-model="configName" required /></label><label>模型名称<input v-model="modelName" required /></label><label class="field-span">Base URL<input v-model="endpoint" type="url" required /></label><label>允许主机<input v-model="host" placeholder="例如：api.openai.com" required /><small class="field-help">仅填写允许连接的 API 域名；多个域名用逗号分隔，不填写协议或路径。</small></label><label>API Key<input v-model="apiKey" type="password" autocomplete="off" required /></label></div><div class="model-dialog__footer"><button type="button" @click="closeDialog">取消</button><button class="primary" type="submit">保存</button></div></form></div>
</template>
