<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { createExport, downloadExport, listExports, type ExportRecord } from '../api/exports'
import { deleteFact, deleteFacts, getFact, listFacts, type Fact } from '../api/facts'
import { listProjects, type Project } from '../api/projects'
import { useAuthStore } from '../stores/auth'
import FactDetailDrawer from '../components/facts/FactDetailDrawer.vue'
const auth = useAuthStore(); const canExport = computed(() => auth.hasPermission('exports:create')); const canDelete = computed(() => auth.hasRole('admin') && auth.hasPermission('records:review'))
const projects = ref<Project[]>([]); const projectId = ref(''); const facts = ref<Fact[]>([]); const total = ref(0); const offset = ref(0); const pageSize = 50; const selected = ref<Fact | null>(null); const selectedFactIds = ref<string[]>([]); const subject = ref(''); const property = ref(''); const reviewStatus = ref(''); const includeUnreviewed = ref(false); const error = ref(''); const notice = ref(''); const exports = ref<ExportRecord[]>([])
const page = computed(() => Math.floor(offset.value / pageSize) + 1); const pageCount = computed(() => Math.max(1, Math.ceil(total.value / pageSize)))
const allVisibleSelected = computed(() => facts.value.length > 0 && facts.value.every((fact) => selectedFactIds.value.includes(fact.id)))
const reviewLabels: Record<string, string> = { candidate: '待评审', candidate_review: '待评审', approved: '已通过', rejected: '已驳回' }
type SaveFileHandle = { createWritable(): Promise<{ write(data: Blob): Promise<void>; close(): Promise<void> }> }
type SaveFilePicker = (options: { suggestedName: string }) => Promise<SaveFileHandle>
let controller: AbortController | null = null; let generation = 0
function beginRequest() { controller?.abort(); controller = new AbortController(); return { signal: controller.signal, current: ++generation, project: projectId.value } }
function isCurrent(current: number, project: string) { return current === generation && project === projectId.value }
async function loadAll() { const request = beginRequest(); if (!request.project) return; const query = new URLSearchParams({ offset: String(offset.value), limit: String(pageSize) }); if (subject.value) query.set('subject', subject.value); if (property.value) query.set('property', property.value); if (reviewStatus.value) query.set('review_status', reviewStatus.value); try { const [result, history] = await Promise.all([listFacts(request.project, query, request.signal), canExport.value ? listExports(request.project, request.signal) : Promise.resolve({ items: [] as ExportRecord[] })]); if (isCurrent(request.current, request.project)) { facts.value = result.items; selectedFactIds.value = []; total.value = result.total; exports.value = history.items } } catch (reason) { if (!(reason instanceof DOMException && reason.name === 'AbortError') && isCurrent(request.current, request.project)) error.value = '结果暂时无法载入' } }
function toggleVisibleFacts() { selectedFactIds.value = allVisibleSelected.value ? [] : facts.value.map((fact) => fact.id) }
function applyFilters() { offset.value = 0; selectedFactIds.value = []; void loadAll() }
function previousPage() { if (offset.value > 0) { offset.value = Math.max(0, offset.value - pageSize); selectedFactIds.value = []; void loadAll() } }
function nextPage() { if (offset.value + pageSize < total.value) { offset.value += pageSize; selectedFactIds.value = []; void loadAll() } }
watch(projectId, () => { selected.value = null; selectedFactIds.value = []; facts.value = []; exports.value = []; offset.value = 0; void loadAll() }); onMounted(async () => { projects.value = await listProjects(); projectId.value = projects.value[0]?.id || '' }); onBeforeUnmount(() => { generation++; controller?.abort() })
async function exportFacts(format: 'tsv' | 'csv' | 'json') { if (!canExport.value) return; const request = beginRequest(); try { const record = await createExport(request.project, format, includeUnreviewed.value, request.signal); if (!isCurrent(request.current, request.project)) return; notice.value = `导出已生成：${record.record_count} 条，SHA-256 ${record.sha256}`; await loadAll() } catch (reason) { if (!(reason instanceof DOMException && reason.name === 'AbortError') && isCurrent(request.current, request.project)) error.value = '导出未能完成' } }
async function download(record: ExportRecord) { const request = beginRequest(); try { const blob = await downloadExport(request.project, record.id, request.signal); if (!isCurrent(request.current, request.project)) return; const filename = `export-${record.id}.${record.format}`; const picker = (window as Window & { showSaveFilePicker?: SaveFilePicker }).showSaveFilePicker; if (picker) { try { const handle = await picker({ suggestedName: filename }); const writable = await handle.createWritable(); await writable.write(blob); await writable.close(); notice.value = '导出文件已保存到所选位置'; return } catch (reason) { if (reason instanceof DOMException && reason.name === 'AbortError') return; throw reason } } const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url) } catch (reason) { if (!(reason instanceof DOMException && reason.name === 'AbortError') && isCurrent(request.current, request.project)) error.value = '导出文件暂时无法保存' } }
async function openFact(fact: Fact) { const request = beginRequest(); try { const detail = await getFact(request.project, fact.id, request.signal); if (isCurrent(request.current, request.project)) selected.value = detail } catch (reason) { if (!(reason instanceof DOMException && reason.name === 'AbortError') && isCurrent(request.current, request.project)) error.value = '结果详情暂时无法载入' } }
async function removeFact(fact: Fact) { if (!confirm(`删除事实“${fact.subject} - ${fact.property}”？该操作会保留审计历史，但不会再显示在事实结果中。`)) return; error.value = ''; notice.value = ''; try { await deleteFact(projectId.value, fact.id); if (selected.value?.id === fact.id) selected.value = null; notice.value = '事实已删除并保留审计记录。'; if (facts.value.length === 1 && offset.value > 0) offset.value -= pageSize; await loadAll() } catch { error.value = '事实未能删除。它可能正由其他评审员处理，请稍后重试。' } }
async function removeSelectedFacts() { const factIds = [...selectedFactIds.value]; if (!factIds.length || !confirm(`删除已选择的 ${factIds.length} 条事实？该操作会保留审计历史，但不会再显示在事实结果中。`)) return; error.value = ''; notice.value = ''; try { await deleteFacts(projectId.value, factIds); if (selected.value && factIds.includes(selected.value.id)) selected.value = null; selectedFactIds.value = []; notice.value = `已删除 ${factIds.length} 条事实并保留审计记录。`; if (facts.value.length === factIds.length && offset.value > 0) offset.value -= pageSize; await loadAll() } catch { error.value = '所选事实未能删除。它们可能正由其他评审员处理，请刷新后重试。' } }
</script>
<template><section class="facts-page" aria-labelledby="facts-title"><p class="eyebrow">抽取结果</p><h1 id="facts-title">事实结果</h1><form class="filter-bar" @submit.prevent="applyFilters"><label>项目<select v-model="projectId"><option v-for="project in projects" :key="project.id" :value="project.id">{{ project.name }}</option></select></label><label>主体<input v-model="subject" /></label><label>关系<input v-model="property" /></label><label>评审状态<select v-model="reviewStatus"><option value="">全部</option><option value="candidate">待评审</option><option value="approved">已通过</option><option value="rejected">已驳回</option></select></label><button type="submit">筛选</button></form>
  <div class="toolbar"><span>共 {{ total }} 条</span><template v-if="canDelete"><span class="muted">已选 {{ selectedFactIds.length }} 条</span><button class="danger-button" type="button" :disabled="!selectedFactIds.length" @click="removeSelectedFacts">删除所选</button></template><template v-if="canExport"><label class="check-row"><input v-model="includeUnreviewed" type="checkbox" />包含未评审结果</label><button type="button" @click="exportFacts('tsv')">导出 TSV</button><button type="button" @click="exportFacts('csv')">导出 CSV</button><button type="button" @click="exportFacts('json')">导出 JSON</button></template></div><p v-if="error" role="alert" class="message error">{{ error }}</p><p v-if="notice" role="status" class="message success">{{ notice }}</p>
  <div class="table-wrap"><table><thead><tr><th v-if="canDelete"><input type="checkbox" aria-label="全选当前页事实" :checked="allVisibleSelected" @change="toggleVisibleFacts" /></th><th>主体</th><th>关系</th><th>值</th><th>来源路线</th><th>置信度</th><th>评审状态</th><th>操作</th></tr></thead><tbody><tr v-for="fact in facts" :key="fact.id"><td v-if="canDelete"><input v-model="selectedFactIds" type="checkbox" :value="fact.id" :aria-label="`选择事实 ${fact.subject} - ${fact.property}`" /></td><td>{{ fact.subject }}</td><td>{{ fact.property }}</td><td class="evidence-text">{{ fact.value }}</td><td>{{ fact.route }} / {{ fact.extraction_source }}</td><td>{{ fact.confidence ?? '—' }}</td><td><span class="status" :class="`status--${fact.review_status}`">{{ reviewLabels[fact.review_status] || fact.review_status }}</span></td><td class="fact-actions"><button type="button" @click="openFact(fact)">完整结果及溯源信息</button><button v-if="canDelete" class="danger-button" type="button" @click="removeFact(fact)">删除</button></td></tr><tr v-if="!facts.length"><td :colspan="canDelete ? 8 : 7" class="empty-cell">当前筛选条件下没有结果</td></tr></tbody></table></div><div class="pagination"><button type="button" :disabled="offset === 0" @click="previousPage">上一页</button><span>第 {{ page }} / {{ pageCount }} 页</span><button type="button" :disabled="offset + pageSize >= total" @click="nextPage">下一页</button></div>
  <section v-if="canExport" aria-labelledby="exports-title"><h2 id="exports-title">导出历史</h2><div class="table-wrap"><table><thead><tr><th>格式</th><th>记录数</th><th>状态</th><th>文件大小</th><th>SHA-256</th><th>操作</th></tr></thead><tbody><tr v-for="record in exports" :key="record.id"><td>{{ record.format.toUpperCase() }}</td><td>{{ record.record_count }}</td><td>{{ record.status === 'completed' ? '已完成' : '处理中' }}</td><td>{{ record.size_bytes }} B</td><td class="hash">{{ record.sha256 }}</td><td><button type="button" :disabled="record.status !== 'completed'" @click="download(record)">选择保存位置</button></td></tr></tbody></table></div></section><FactDetailDrawer :open="Boolean(selected)" :fact="selected" @close="selected = null" /></section></template>
