<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { getUsage, type UsageItem } from '../api/usage'
import { listProjects, type Project } from '../api/projects'
const projects = ref<Project[]>([]); const projectId = ref(''); const groupBy = ref('model'); const items = ref<UsageItem[]>([]); const error = ref('')
const filters = ref({ user_id: '', batch_id: '', document_id: '', model_config_id: '', purpose: '', status: '', start: '', end: '' })
let controller: AbortController | null = null; let generation = 0
async function load() { controller?.abort(); controller = new AbortController(); const current = ++generation; const query = new URLSearchParams({ group_by: groupBy.value, offset: '0', limit: '100' }); if (projectId.value) query.set('project_id', projectId.value); for (const [key, value] of Object.entries(filters.value)) if (value) query.set(key, key === 'start' || key === 'end' ? new Date(value).toISOString() : value); try { const page = await getUsage(query, controller.signal); if (current === generation) items.value = page.items } catch (reason) { if (!(reason instanceof DOMException && reason.name === 'AbortError') && current === generation) error.value = '用量数据暂时无法载入' } }
onMounted(async () => { try { projects.value = await listProjects(); projectId.value = projects.value[0]?.id || ''; await load() } catch { error.value = '用量数据暂时无法载入' } }); onBeforeUnmount(() => { generation++; controller?.abort() })
</script>
<template><section aria-labelledby="usage-title"><p class="eyebrow">统计与成本</p><h1 id="usage-title">模型用量</h1><form class="filter-bar" @submit.prevent="load"><label>项目<select v-model="projectId"><option value="">全部可见项目</option><option v-for="project in projects" :key="project.id" :value="project.id">{{ project.name }}</option></select></label><label>分组<select v-model="groupBy"><option value="model">模型</option><option value="user">用户</option><option value="batch">批次</option><option value="document">文档</option><option value="purpose">用途</option><option value="status">状态</option></select></label><label>用户编号<input v-model.trim="filters.user_id" /></label><label>批次编号<input v-model.trim="filters.batch_id" /></label><label>文档编号<input v-model.trim="filters.document_id" /></label><label>模型编号<input v-model.trim="filters.model_config_id" /></label><label>用途<input v-model.trim="filters.purpose" maxlength="64" /></label><label>调用状态<select v-model="filters.status"><option value="">全部</option><option value="success">成功</option><option value="failure">失败</option><option value="retry">重试</option><option value="cache_hit">缓存命中</option></select></label><label>开始时间<input v-model="filters.start" type="datetime-local" /></label><label>结束时间<input v-model="filters.end" type="datetime-local" /></label><button type="submit">应用筛选</button></form><p v-if="error" role="alert" class="message error">{{ error }}</p><div class="table-wrap"><table><thead><tr><th>分组</th><th>调用数</th><th>输入 Tokens</th><th>输出 Tokens</th><th>缓存 Tokens</th><th>总 Tokens</th><th>费用</th></tr></thead><tbody><tr v-for="item in items" :key="`${item.key}-${item.currency}`"><td>{{ item.key }}</td><td>{{ item.calls }}</td><td>{{ item.prompt_tokens }}</td><td>{{ item.completion_tokens }}</td><td>{{ item.cached_tokens }}</td><td>{{ item.total_tokens }}</td><td>{{ item.cost }} {{ item.currency }}</td></tr></tbody></table></div></section></template>
